### ISSUE TITLE
Failed to replay 13.1.0 replay files (lesta server)

### ISSUE THREAD

**Issue by ptzpanzer** [Monstrofil/replays_unpack#31]
Hello!

Thanks for your work, I'm developing some simple replay filtering functionality based on your repo.

After updating to the latest replay_unpack from this repo, I'm trying to open a 13.1.0 version of lesta server replay with my code (working normally in v12.11.0). But the following error was reported:

`ERROR:root:Problem with packet 0.0:5:<class 'replays_unpack.replay_unpack.clients.wows.network.packets.EntityCreate.EntityCreate'>
Traceback (most recent call last):
  File "E:\Download\IDMDownload\Compressed\replays_filter\./replays_unpack\replay_unpack\core\network\player.py", line 36, in play
    self._process_packet(packet.time, self._deserialize_packet(packet))
  File "E:\Download\IDMDownload\Compressed\replays_filter\replays_unpack\replay_unpack\clients\wows\player.py", line 105, in _process_packet
    entity.set_client_property(idx, values)
  File "E:\Download\IDMDownload\Compressed\replays_filter\./replays_unpack\replay_unpack\core\entity.py", line 136, in set_client_property
    prop = self.client_properties[exposed_index]
IndexError: list index out of range
Traceback (most recent call last):
  File "E:\Download\IDMDownload\Compressed\replays_filter\./replays_unpack\replay_unpack\core\network\player.py", line 36, in play
    self._process_packet(packet.time, self._deserialize_packet(packet))
  File "E:\Download\IDMDownload\Compressed\replays_filter\replays_unpack\replay_unpack\clients\wows\player.py", line 105, in _process_packet
    entity.set_client_property(idx, values)
  File "E:\Download\IDMDownload\Compressed\replays_filter\./replays_unpack\replay_unpack\core\entity.py", line 136, in set_client_property
    prop = self.client_properties[exposed_index]
IndexError: list index out of range`

I tried to open other reps with your code, and it also reported a series of errors, such as:

`ERROR:root:Problem with packet 226.25270080566406:35:<class 'replay_unpack.core.packets.NestedProperty.NestedProperty'>
Traceback (most recent call last):
  File "E:\Download\IDMDownload\Compressed\replays_unpack-master_2\replays_unpack-master\replay_unpack\core\network\player.py", line 36, in play
    self._process_packet(packet.time, self._deserialize_packet(packet))
  File "E:\Download\IDMDownload\Compressed\replays_unpack-master_2\replays_unpack-master\replay_unpack\clients\wows\player.py", line 170, in _process_packet
    e = self._battle_controller.entities[packet.entity_id]
KeyError: 775324`

Will this repo still update the Lesta server client? (I am deeply concerned as more and more developers choose to discontinue support for Lesta) If not, could you pls guide me in understanding and fixing the above error?

This is the rep I used for testing:
[test.zip](https://github.com/Monstrofil/replays_unpack/files/14577355/test.zip)

**Comment by Monstrofil** [comment]
Hi, I dropped support for Lesta unless somebody is going to pay for it.

Error that you show either means that you use wrong .def files (they are different in eu and ru games) or Lesta changed underlying protocol a little bit which would be a pain to fix.
